const INFO = {
    european_aqi: {
      tag: 'European AQI',
      title: 'About this index',
      body: 'The European Air Quality Index combines readings from five key pollutants — PM2.5, PM10, NO₂, O₃, and SO₂ — into a single score using EU directive standards. A score below 20 is considered good; values above 50 may pose risk to sensitive groups including the elderly and those with respiratory conditions.',
      bands: [
        { label: 'Good',      range: '0 – 20'  },
        { label: 'Fair',      range: '20 – 40' },
        { label: 'Moderate',  range: '40 – 60' },
        { label: 'Poor',      range: '60 – 80' },
        { label: 'Very poor', range: '80 – 100'},
      ],
    },
    pm2_5: {
      tag: 'PM2.5',
      title: 'Fine particulate matter',
      body: 'PM2.5 refers to airborne particles smaller than 2.5 micrometres — fine enough to penetrate deep into the lungs and enter the bloodstream. Primary sources in London include road traffic, wood burning, and secondary formation from gas emissions. The WHO annual guideline is 5 μg/m³.',
      bands: [
        { label: 'Good',      range: '0 – 10 μg/m³'  },
        { label: 'Fair',      range: '10 – 20 μg/m³' },
        { label: 'Moderate',  range: '20 – 25 μg/m³' },
        { label: 'Poor',      range: '25 – 50 μg/m³' },
        { label: 'Very poor', range: '> 50 μg/m³'    },
      ],
    },
    pm10: {
      tag: 'PM10',
      title: 'Coarse particulate matter',
      body: 'PM10 particles are up to 10 micrometres in diameter and are typically generated by construction dust, road surface wear, and natural sources such as pollen and sea salt. While less penetrating than PM2.5, elevated levels can still aggravate asthma and cardiovascular disease. The WHO daily guideline is 45 μg/m³.',
      bands: [
        { label: 'Good',      range: '0 – 20 μg/m³'  },
        { label: 'Fair',      range: '20 – 40 μg/m³' },
        { label: 'Moderate',  range: '40 – 50 μg/m³' },
        { label: 'Poor',      range: '50 – 100 μg/m³'},
        { label: 'Very poor', range: '> 100 μg/m³'   },
      ],
    },
    no2: {
      tag: 'NO₂',
      title: 'Nitrogen dioxide',
      body: 'Nitrogen dioxide is produced primarily by combustion engines and gas boilers. It irritates the airways and is a precursor to both ground-level ozone and secondary particulate matter. London has historically struggled to meet EU limits for NO₂, particularly along major roads. The WHO annual guideline is 10 μg/m³.',
      bands: [
        { label: 'Good',      range: '0 – 40 μg/m³'  },
        { label: 'Fair',      range: '40 – 90 μg/m³' },
        { label: 'Moderate',  range: '90 – 120 μg/m³'},
        { label: 'Poor',      range: '120 – 230 μg/m³'},
        { label: 'Very poor', range: '> 230 μg/m³'   },
      ],
    },
    o3: {
      tag: 'O₃',
      title: 'Ground-level ozone',
      body: 'Unlike stratospheric ozone, ground-level ozone is a secondary pollutant formed when NOₓ and volatile organic compounds react in sunlight. Levels peak on hot, sunny days and are often higher in outer London suburbs than central areas. It can trigger breathing difficulties, particularly during exercise. The EU target value is 120 μg/m³.',
      bands: [
        { label: 'Good',      range: '0 – 50 μg/m³'  },
        { label: 'Fair',      range: '50 – 100 μg/m³'},
        { label: 'Moderate',  range: '100 – 130 μg/m³'},
        { label: 'Poor',      range: '130 – 240 μg/m³'},
        { label: 'Very poor', range: '> 240 μg/m³'   },
      ],
    },
    so2: {
      tag: 'SO₂',
      title: 'Sulphur dioxide',
      body: 'Sulphur dioxide is released by burning fossil fuels containing sulphur, particularly diesel and coal. Levels in London have fallen significantly since the Clean Air Acts but can still spike near industrial sites and ports. Short-term exposure at elevated levels can trigger asthma attacks. The EU daily limit is 125 μg/m³.',
      bands: [
        { label: 'Good',      range: '0 – 100 μg/m³' },
        { label: 'Fair',      range: '100 – 200 μg/m³'},
        { label: 'Moderate',  range: '200 – 350 μg/m³'},
        { label: 'Poor',      range: '350 – 500 μg/m³'},
        { label: 'Very poor', range: '> 500 μg/m³'   },
      ],
    },
  };
  
  export default function PollutantInfo({ pollutantKey }) {
    const info = INFO[pollutantKey];
    if (!info) return null;
  
    return (
      <div className="pollutant-info">
        <div className="info-tag">{info.tag}</div>
        <h2 className="info-title">{info.title}</h2>
        <p className="info-body">{info.body}</p>
        <div className="info-bands">
          {info.bands.map(b => (
            <div key={b.label} className="info-band">
              <span className="band-label">{b.label}</span>
              <span className="band-range">{b.range}</span>
            </div>
          ))}
        </div>
      </div>
    );
  }